name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: "27 19 * * *"
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      php-versions: ${{ steps.fetch.outputs.supported }}
      json: ${{ steps.fetch.outputs.json }}
      latest: ${{ steps.fetch.outputs.latest }}
    steps:
      - name: fetch versions
        id: fetch
        run: |
          set -x

          echo -n "json=" >> "$GITHUB_OUTPUT"
          curl -cv --retry 3 https://www.php.net/releases/index.php?json | \
            tee /tmp/json >> "$GITHUB_OUTPUT"
          cat /tmp/json | jq
          echo -en "\nsupported=" >> "$GITHUB_OUTPUT"
          cat /tmp/json | \
            jq -c 'reduce .[].supported_versions as $item ([];. + $item)' \
            >> "$GITHUB_OUTPUT"
          echo -en "\nlatest=" >> "$GITHUB_OUTPUT"
          cat /tmp/json | \
            jq -c '.[keys | max].version | split(".") | ""+.[0]+"."+.[1]' \
            >> "$GITHUB_OUTPUT"
          echo >> "$GITHUB_OUTPUT"
#temp disable until i get chaching to work
#  build-base:
#    runs-on: ubuntu-latest
#    needs: [make-matrix]
#    strategy:
#      fail-fast: false
#      matrix:
#        version: ${{ fromJson(needs.make-matrix.outputs.php-versions) }}
#        type: [fpm]
#    permissions:
#      contents: read
#    steps:
#      - uses: actions/checkout@v4
#      - uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1
#      - uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
#        with:
#          context: .
#          file: base.Dockerfile
#          cache-to: type=gha,mode=max
#          cache-from: type=gha
#          build-args: |
#            VERSION=${{ matrix.version }}
#            VARIANT=${{ matrix.variant }}

  build:
    runs-on: ubuntu-latest
    needs: [make-matrix]
    outputs:
      ids: ${{ steps.build-and-push.outputs.digest }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.make-matrix.outputs.php-versions) }}
        type: [cli, fpm]
        variant: [prod, dev]
    name: ${{ format('php:{0}-{1}-{2}', matrix.version, matrix.type, matrix.variant) }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          registry: docker.io
          username: borrel
          password: ${{ secrets.DOCKER_KEY }}

      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        with:
          registry: ghcr.io
          username: Borrel/PHPUtils
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f # v5.8.0
        with:
          images: |
            docker.io/borrel/php
            ghcr.io/Borrel/PHPUtils
          tags: |
            type=raw,value=latest,enable=${{ matrix.version == fromJson(needs.make-matrix.outputs.latest) && (matrix.type == 'cli') && matrix.variant == 'prod'}}
            type=raw,value=${{matrix.type}},enable=${{ matrix.version == fromJson(needs.make-matrix.outputs.latest) && matrix.variant == 'prod' }}
            type=raw,value=${{matrix.type}}-latest,enable=${{ matrix.version == fromJson(needs.make-matrix.outputs.latest) && matrix.variant == 'prod'}}

            type=raw,value=${{matrix.type}}-latest-${{matrix.variant}},enable=${{(matrix.version == fromJson(needs.make-matrix.outputs.latest)) }}
            type=raw,value=${{matrix.type}}-${{matrix.variant}},enable=${{(matrix.version == fromJson(needs.make-matrix.outputs.latest)) }}

            type=raw,value=${{matrix.variant}},enable=${{(matrix.version == fromJson(needs.make-matrix.outputs.latest))  && (matrix.type == 'cli') }}

            type=raw,value=${{matrix.type}}-${{matrix.version}},enable=${{matrix.variant == 'prod'}}
            type=raw,value=${{matrix.type}}-${{matrix.version}}-${{matrix.variant}}

      - name: build and push
        id: build-and-push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          pull: false
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main'}}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
          cache-to: type=gha,mode=max
          cache-from: type=gha
          build-args: |
            VERSION=${{ matrix.version }}
            FLAVOR=${{ matrix.type }}
            VARIANT=${{ matrix.variant }}

      - name: extract build info
        run: |
          docker create --name tmp docker.io/borrel/php:${{ matrix.type }}-${{ matrix.version }}-${{ matrix.variant }}
          docker cp tmp:/README.md /tmp/README-${{ matrix.type }}-${{ matrix.version }}-${{ matrix.variant }}.md
          cat /tmp/README-${{ matrix.type }}-${{ matrix.version }}-${{ matrix.variant }}.md >> $GITHUB_STEP_SUMMARY
