name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: "27 19 * * *"
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ vars.DOCKER_USER }}/PHPUtils

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      php-versions: ${{steps.fetch.outputs.supported}}
      json: ${{steps.fetch.outputs.json}}
      latest: ${{steps.fetch.outputs.latest}}
    steps:
      - name: fetch versions
        id: fetch
        run: |
          set -x

          echo -n "json=" >> "$GITHUB_OUTPUT"
          curl -cv --retry 3 https://www.php.net/releases/index.php?json | \
            tee /tmp/json >> "$GITHUB_OUTPUT"
          cat /tmp/json | jq
          echo -en "\nsupported=" >> "$GITHUB_OUTPUT"
          cat /tmp/json | \
            jq -c 'reduce .[].supported_versions as $item ([];. + $item)' \
            >> "$GITHUB_OUTPUT"
          echo -en "\nlatest=" >> "$GITHUB_OUTPUT"
          cat /tmp/json | \
            jq -c '.[keys | max].version | split(".") | ""+.[0]+"."+.[1]' \
            >> "$GITHUB_OUTPUT"
          echo >> "$GITHUB_OUTPUT"

  build:
    runs-on: ubuntu-latest
    needs: [make-matrix]
    outputs:
      ids: ${{steps.build-and-push.outputs.digest}}
    strategy:
      fail-fast: false
      matrix:
        version: ${{fromJson(needs.make-matrix.outputs.php-versions)}}
        type: [cli, apache, fpm]
    name: php:${{ matrix.version }}-${{matrix.type}}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - id: ceckout
        name: Checkout repository
        uses: actions/checkout@v4

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - id: setup-cosigin
        name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da # v3.7.0
        with:
          cosign-release: "v2.2.4"

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - id: setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - id: login-docker
        name: Log into registry docker.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: docker.io
          username: borrel01
          password: ${{ secrets.DOCKER_KEY }}

      - id: login-github
        name: Log into registry github
        if: github.event_name != 'pull_request'
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: Borrel/PHPUtils
          password: ${{ secrets.GITHUB_TOKEN }}
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: debug
        run: |
          echo type ${{matrix.type}} ${{matrix.type == 'cli'}}
          echo 'version "${{matrix.version}}" == "${{fromJson(needs.make-matrix.outputs.latest)}}" ${{matrix.version == fromJson(needs.make-matrix.outputs.latest)}}'
          echo ref ${{github.ref}} ${{github.ref == 'refs/heads/main'}}
          echo res ${{(matrix.version == fromJson(needs.make-matrix.outputs.latest)) && (github.ref == 'refs/heads/main') && (matrix.type == 'cli')}}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: |
            docker.io/borrel01/phputils
            ghcr.io/Borrel/PHPUtils
          tags: |
            type=raw,value=${{matrix.type}}-${{matrix.version}},enable=${{github.ref == 'refs/heads/main'}}
            type=raw,value=${{matrix.type}},enable=${{(matrix.version == fromJson(needs.make-matrix.outputs.latest)) && (github.ref == 'refs/heads/main')}}
            type=raw,value=${{matrix.type}}-latest,enable=${{(matrix.version == fromJson(needs.make-matrix.outputs.latest)) && (github.ref == 'refs/heads/main')}}
            type=raw,value=latest,enable=${{(matrix.version == fromJson(needs.make-matrix.outputs.latest)) && (github.ref == 'refs/heads/main') && (matrix.type == 'cli')}}
      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ matrix.version }}
            FLAVOR=${{ matrix.type }}

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.imageid }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
